### ISSUE TITLE
BMP svg block diagram is missing

### ISSUE THREAD

**Issue by mofosyne** [kaitai-io/kaitai_struct_formats#692] opened 2024-05-21 14:56 UTC
In https://formats.kaitai.io/bmp/ was expecting https://formats.kaitai.io/bmp/bmp.svg to render, but turns out it's missing.

**Comment by generalmimon** [comment] 2024-05-21 16:28
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/1001

**Closed by generalmimon** 2024-05-21 16:28 UTC
Labels: duplicate
