### ISSUE TITLE
Argument 3: cannot convert from 'Kaitai.Wav' to 'Kaitai.Riff'

### ISSUE THREAD

**Issue by doctor30306** [kaitai-io/kaitai_struct_formats#609] opened 2022-05-23 17:05 UTC
Hi.  I am using C# code generated from the wav.ksy file on your WebIDE.

I am getting an error on line 346 in wav.cs that says: "Argument 3: cannot convert from 'Kaitai.Wav' to 'Kaitai.Riff'"

```cs
public Wav(KaitaiStream p__io, KaitaiStruct p__parent = null, Wav p__root = null) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root ?? this;
            f_subchunks = false;
            f_parentChunkData = false;
            f_isFormTypeWave = false;
            f_isRiffChunk = false;
            f_chunkId = false;
            f_formType = false;
            _read();
        }
        private void _read()
        {
            _chunk = new Riff.Chunk(m_io, this, **m_root**);
        }
```

m_root is of type Wav but Riff.Chunk is expecting m_root to be of type Riff.

I am new to this and not clear on how to resolve this problem in the ksy file....

Any guidance would be appreciated!

**Comment by generalmimon** [comment] 2024-03-18 09:14
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/963

**Closed by generalmimon** 2024-03-18 09:14 UTC
Labels: bug, duplicate
